#!/bin/bash

# Create a new repository from the git restricted shell
#
# Specify: repository name, optionally: description

dir="`basename \"$1\" .git`.git"
shift

if [ -z "$dir" ]
then
	echo "Specify new repo as ssh `hostname` new reponame"
	exit 1
fi

if [ -e "$dir" ]
then
	echo "\"$1\" Exists"
	exit 1
fi

if ! git init --bare "$dir"
then
	echo "Failed"
	exit 1
fi
if test -n "$*"
then
	echo "$*" >"$dir/description"
fi
echo "URL is git@`hostname`:$dir"
exit 0

